name: Continuous Integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

paths-ignore:
  - node_modules
  - dist
  - README.md

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github-token: ${{ secrets.MDEFENDERS_GITHUB_TOKEN }}
          workflows-to-call:
            '{ "mdefenders/it-delivers-everywhere-gitops": { "yaml":
            "cd-update-gitops.yaml", "ref": "main", "data": { "gitops-branch":
            "main", "new-tag": "0.0.1", "gitops-file": "test/manifest.yaml",
            "environment": "production", "image":
            "ghcr.io/mdefenders/app:0.0.1", "app": "my-app-back", "replicas":
            "3", "rollback": "false", "dry-run": "false" } } }'
